baseURL = "https://fibra.click"
languageCode = "it-IT"
title = "FibraClick Wiki"

theme = "fibraclick"

removePathAccents = true

[params]
  homeTitle = "FibraClick Wiki, risposte sulla fibra ottica"
  description = "Dubbi su fibra ottica, banda ultralarga o reti in generale? FibraClick è lo spazio dedicato dove trovare risposte precise e affidabili."
  analytics = true
  ads = true

[permalinks]
  posts = "/:slug"
  categories = "/c/:slug"

[taxonomies]
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingIDType = "blackfriday"

[author]
  email = "info@fibraclick.it"
